services:
  hmpps-prisoner-base-location-api:
    image: ghcr.io/ministryofjustice/hmpps-prisoner-base-location-api:latest
    networks:
      - hmpps
    container_name: hmpps-prisoner-base-location-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - PRODUCT_ID=DPS037
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
    env_file: .env.docker

networks:
  hmpps:
