hmpps-auth.url: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"

api.client:
  health-timeout: 2s
  clients:
    prisoner-offender-search:
      base-url: "https://prisoner-search-dev.prison.service.justice.gov.uk"
      response-timeout: 20s
