server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

services:
  hmpps-auth:
    base-url: http://localhost:3000
    username: client
    password: client-secret
  prisoner-offender-search:
    base-url: http://localhost:4000
  ndelius:
    base-url: http://localhost:4014

hmpps:
  auth:
    url: http://localhost:3000/auth